# Copyright (C) 2019 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/sdm845-common/setup-makefiles.sh
VENDOR_PATH=vendor/samsung/sdm845-common

# include blob-finder
#include vendor/samsung/sdm845-common/find-vendor-blobs.mk

PRODUCT_PACKAGES += \
    ImsSettings \
    HotwordEnrollmentOKGoogleExWCD9340 \
    HotwordEnrollmentXGoogleExWCD9340 \
    vzw_msdc_api \
    imsservice \
    QAS_DVC_MSP_VZW \
    VZWAPNService_sku \
    VZWAPNLib_VZW

# common proprietary blobs
#PRODUCT_COPY_FILES += $(call find-vendor-blobs,vendor/samsung/sdm845-common/proprietary)


